from os import popen
from os.path import join, dirname, abspath, expanduser
from distutils.dir_util import copy_tree

# move current to ~/betty
home = expanduser("~")
current_dir = dirname(abspath('install.py'))
copy_tree(current_dir, join(home, 'betty'))
print "Betty is installed to ~/betty/"

# append to .SHELLrc
SHELL = popen("echo $SHELL").read()
SHELL = SHELL[:-1] # no \n
SHELL = SHELL.split('/')[-1] # the name of the current shell

shell_config = join(expanduser("~"), '.'+SHELL+'rc')
print("Writing to "+shell_config+". Is this okay? Press <Enter> if so")
if raw_input('> ') == '':
    file = open(shell_config, 'a+')
    full_path = join(home, 'betty', 'main.rb')
    file.write('\n####### Generated by an automatic shell script to install betty\n')
    file.write('alias betty='+full_path+'\n')
    print "alias betty=~/betty/main.rb written to the end of rc file"
    file.close()
else:
    print("Okay, not writing anywhere.")
