require 'readline'

def ask(prompt="", newline=false)
  prompt += "\n" if newline
  Readline.readline(prompt, true).squeeze(" ").strip
end

puts "We will install to ~/betty and put an alias in your .<shell>rc. Hit <enter> or 'y' if this is okay."
STDOUT.flush
CONTINUE = ask "> "
if CONTINUE == "" || CONTINUE == "y"
    # copy to ~/betty/
    INSTALL_LOC = Dir.home + '/betty/'
    COPY_COMMAND = 'cp -rf '+ Dir.pwd + ' ' + INSTALL_LOC
    print "Running `" + COPY_COMMAND + "`\n"
    system COPY_COMMAND 

    # get current shell
    *junk, SHELL = `echo $SHELL`.split('/')

    # writing the alias
    SHELLRC = (Dir.home + '/.' + SHELL.chomp + 'rc').chomp
    print "Writing an alias called `betty` to " + SHELLRC + "\n"
    open(SHELLRC, 'a') do |f|
      f.puts "\n"
      f.puts "######## Generated by Betty's install script"
      f.puts "alias betty=#{ Dir.home }/betty/main.rb"
    end
end
