# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require_relative '../main.rb'

RSpec.configure do |config|

  # Default our subject to run betty with the context
  config.before(:all) do
    self.class.subject do
      interpret(self.class.description)
    end
  end

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

# Some custom test vocabulary
#
def responds_with(something)
  should(include(something))
end
